### ISSUE TITLE
go panic on exit (sometimes)

### ISSUE THREAD

**Issue by matti** [jakolehm/nightwatch#10]
started without debug:
```
find . | nightwatch --exit-on-change=255 bundle exec ruby wsvnc.rb
```

```
wsvnc_1                    | shutting down
wsvnc_1                    | panic: runtime error: invalid memory address or nil pointer dereference
wsvnc_1                    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c6fa1]
wsvnc_1                    |
wsvnc_1                    | goroutine 58 [running]:
wsvnc_1                    | os.(*Process).signal(0x0, 0x661f00, 0x65c068, 0x0, 0x0)
wsvnc_1                    | 	/usr/local/go/src/os/exec_unix.go:56 +0x31
wsvnc_1                    | os.(*Process).Signal(...)
wsvnc_1                    | 	/usr/local/go/src/os/exec.go:131
wsvnc_1                    | main.runCommand.func3(0xc00012c000, 0xc000018a18, 0xc00008c580, 0xc00000e0a8)
wsvnc_1                    | 	/src/nightwatch/main.go:168 +0x109
wsvnc_1                    | created by main.runCommand
wsvnc_1                    | 	/src/nightwatch/main.go:159 +0x2aa
wsvnc_1                    |
wsvnc_1                    |   -- restart (entrypoint.sh)
wsvnc_1                    | wsvnc listening at 0.0.0.0:8080
wsvnc_1                    | TERM (wsvnc.rb)
wsvnc_1                    | shutting down
```

**Comment by matti** [comment]
```
wsvnc_1                    | time="2020-02-24T12:46:27Z" level=debug msg="got signal &{signal:15 exitProcess:false}"
wsvnc_1                    | time="2020-02-24T12:46:27Z" level=debug msg="process started"
wsvnc_1                    | panic: runtime error: invalid memory address or nil pointer dereference
wsvnc_1                    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c6fa1]
wsvnc_1                    |
wsvnc_1                    | goroutine 54 [running]:
wsvnc_1                    | os.(*Process).signal(0x0, 0x661f00, 0x65c068, 0x0, 0x0)
wsvnc_1                    | 	/usr/local/go/src/os/exec_unix.go:56 +0x31
wsvnc_1                    | os.(*Process).Signal(...)
wsvnc_1                    | 	/usr/local/go/src/os/exec.go:131
wsvnc_1                    | main.runCommand.func3(0xc000146000, 0xc00017e0a5, 0xc00008e580, 0xc00017c000)
wsvnc_1                    | 	/src/nightwatch/main.go:168 +0x109
wsvnc_1                    | created by main.runCommand
wsvnc_1                    | 	/src/nightwatch/main.go:159 +0x2aa
wsvnc_1                    |
wsvnc_1                    |   -- restart (entrypoint.sh)
wsvnc_1                    | time="2020-02-24T12:46:28Z" level=debug msg="process started"
wsvnc_1                    | lol
```

**Comment by matti** [comment]
^-- with --debug

**Comment by matti** [comment]
looks like fixed in https://github.com/jakolehm/nightwatch/releases/tag/v0.4.0
